-- local ssh_config = {
--   scp_binary = "/usr/local/bin/scp",
-- }
--
-- local remote = {
--   copy_dirs = {
--     data = {
--       base = vim.fn.stdpath("data"),
--       dirs = {"plugged", "site"},
--       compression = {
--         enabled = true,
--       },
--     },
--   }
-- }
--
-- local progress_view = {
--   type = "split",
-- }
--
-- require("remote-nvim").setup({
--   ssh_config = ssh_config,
--   remote = remote,
--   progress_view = progress_view,
-- })

